### ISSUE TITLE
Degrees revert to C from F

### ISSUE THREAD

**Issue by sweetapus** [gedankenstuecke/Minimal-Clock#3]
The clock periodically reverts the temp display from specific degrees in F to “- -“ C. The only way to fix the display is to sync the device to the app.

**Comment by gedankenstuecke** [comment]
Thanks for reporting that! I noticed it too and I think it happens generally when the Fitbit app on the phone isn't sending the data to the Versa. 

The way it works is that the phone is getting the current location via GPS and does the request for the weather data for that location and sends it to the Versa afterwards, this is automatically triggered from the Versa every 20 minutes or so. If the Fitbit app can't be reached by the Versa it will default to the `--` display. Similar things happen if the Yahoo weather API can't be reached because there's no signal or the phone doesn't have a GPS signal.

I'm not sure what a good fix for this could be, except for making sure that the Fitbit app on the phone needs to be somewhat active (i.e. don't fully swipe it closed on iOS).

**Comment by gedankenstuecke** [comment]
I collected a number of potential reasons of what can go wrong with the temperature display here: https://minimal-clock.readthedocs.io/en/latest/faq.html#the-weather-will-not-update-and-only-displays-instead

Closing this for now.
